config/routes.rb
Rails.application.routes.draw do

   namespace :admin do
    root to: "homes#top"
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :users, only: [:edit, :create, :update, :destroy, :show]
    resources :posts, only: [:index, :edit, :create, :update, :destroy, :new, :show] do
      resources :post_comments, only: [:create, :destroy, :edit, :index, :update]
      resource :group_users, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end



  end




  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PartyAnimal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body class="d-flex flex-column vh-500">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-3 icon" href="/">PARTY ANIMALS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!--ログインしている場合-->
              <% if user_signed_in? %>
                <li class="nav-item m-4">
                  <%= link_to "Home", posts_path, class: "word" %>
                </li>
                <li class="nav-item m-4">
                  <%= link_to "My page", user_path(current_user), class: "word" %>
                </li>
                <li class="nav-item m-4">
                  <%= link_to "Create", new_post_path, class: "word" %>
                </li>
                <li class="nav-item m-4">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "word" %>
                </li>
                <!--ログインしていない場合-->
              <% else %>
                <li class="nav-item m-4">
                   <%= link_to "Home", root_path, class: "word" %>
                </li>
                <li class="nav-item m-4">
                  <%= link_to "Sign up", new_user_registration_path, class: "word" %>
                </li>
                <li class="nav-item m-4">
                   <%= link_to "Log in", new_user_session_path, class: "word" %>
                </li>
                <li class="nav-item m-4">
                    <%= link_to 'Guest log in', users_guest_sign_in_path, class: "word", method: :post %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>